# Generated by Django 3.1.3 on 2022-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, unique=True, verbose_name='날짜')),
                ('temp', models.FloatField(null=True, verbose_name='온도')),
                ('humidity', models.FloatField(null=True, verbose_name='습도')),
                ('CO2', models.FloatField(null=True, verbose_name='CO2')),
            ],
        ),
    ]
